services:
  postgres:
    image: postgres:15-alpine
    container_name: messaging-service-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U messaging_user -d messaging_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ghcr.io/xnoto/messaging-service-app:latest
    container_name: messaging-service-app
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
