---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: messaging-service-ingress
spec:
  rules:
  - host: messaging-service-app.makeitwork.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 8080
