name: Build and Push Docker Image

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ghcr.io/xnoto/messaging-service-app:latest

      - name: Slim it!
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ghcr.io/xnoto/messaging-service-app:latest
          tag: "slim"

      - name: Push to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker image push ghcr.io/xnoto/messaging-service-app --all-tags
