name: Build and Push Docker Image

on:
  push:
    branches: main
  workflow_dispatch:

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: false
          tags: ghcr.io/xnoto/messaging-service-app:latest

      - name: Push to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker image push ghcr.io/xnoto/messaging-service-app --all-tags
